# Generated by Django 2.0.2 on 2021-05-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_internal_normal_surgery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='number',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
