# Generated by Django 2.0.2 on 2021-05-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20210509_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publisher', models.CharField(max_length=128)),
                ('Internaltitle', models.CharField(max_length=128)),
                ('Internaldate', models.DateField(auto_now=True)),
                ('Internalkeywords', models.CharField(max_length=128)),
                ('Internalpreread', models.CharField(max_length=128)),
                ('Internalarticle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publisher', models.CharField(max_length=128)),
                ('Surgerytitle', models.CharField(max_length=128)),
                ('Surgerydate', models.DateField(auto_now=True)),
                ('Surgerykeywords', models.CharField(max_length=128)),
                ('Surgerypreread', models.CharField(max_length=128)),
                ('Surgeryarticle', models.TextField()),
            ],
        ),
    ]
