# Generated by Django 2.0.2 on 2021-05-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('birthday', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Normal',
        ),
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ['c_time'], 'verbose_name': '管理员', 'verbose_name_plural': '管理员'},
        ),
    ]
